---
homebrew_taps: []

homebrew_packages:
  - bat
  - curl
  - dust
  - eza
  - fd
  - fselect
  - fzf
  - git
  - git-lfs
  - glances
  - htop
  - httpie
  - jq
  - lazydocker
  - mas
  - ncdu
  - neovim
  - nnn
  - node
  - nvm
  - onefetch
  - pandoc
  - pass
  - peco
  - pipx
  - procs
  - progress
  - pyenv
  - pyenv-virtualenv
  - ripgrep
  - sd
  - syncthing
  - svn
  - thefuck
  - tldr
  - tmux
  - tree
  - universal-ctags
  - watch
  - wget
  - yt-dlp
  - zoxide
  - zsh

homebrew_casks:
  - appcleaner
  - bartender
  - docker
  - font-hack-nerd-font
  - font-sauce-code-pro-nerd-font
  - google-chrome
  - hammerspoon
  - itsycal
  - netnewswire
  - sf-symbols
  - slack
  - spotify
  - texifier
  - transmission
  - the-unarchiver
  - visual-studio-code
  - vlc
  - zotero

mases:
  - 937984704   # Amphetamine
  - 1278508951  # Trello

homebrew_services:
  - syncthing
