---
sudo: required
dist: trusty

language: python
python: "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13 
  - sudo apt-get update

install:
  # Install pip.
  - sudo easy_install pip

  # Install Ansible.
  - sudo pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory main.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i inventory main.yml -b
