---
# Should be refactored like this one:
# https://github.com/alexdesousa/dotfiles

- hosts: all
  connection: local

  tasks:
    - import_tasks: tasks/user.yml
      tags: user

    - import_tasks: tasks/packages.yml
      tags: packages

    - import_tasks: tasks/node.yml
      tags: node
      when:
        - ansible_os_family != "Darwin"

    - import_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - import_tasks: tasks/fonts.yml
      tags: fonts

    - import_tasks: tasks/zsh.yml
      tags: zsh

    - import_tasks: tasks/tmux.yml
      tags: tmux

    - import_tasks: tasks/spacevim.yml
      tags: spacevim

