---
- block:

  - name: Checks if .dofiles exists in home path
    stat:
      path: "{{ home_path }}/.dotfiles"
    register: dotfiles_stat

  - name: Copy dotfiles folder
    copy:
      src: files
      dest: "{{ dotfiles_home }}/"
    when: not dotfiles_stat.stat.exists

  - name: Remove jinja2 suffices
    template:
      src: "{{ item }}"
      dest: '{{ item | regex_replace("\.j2$", "") }}'
    with_fileglob:
      - "{{ dotfiles_home }}/files/link/*.j2"

  - name: Link dotfiles
    file:
      src: "{{ dotfiles_home }}/files/link/{{ item }}"
      dest: "/{{ home_path }}/.{{ item }}"
      state: link
      force: true
    with_items: "{{ linked_dotfiles }}"

  # - name: Link vim config
  #   file:
  #     src: "{{ dotfiles_home }}/files/link/vim"
  #     dest: "/home/{{ username }}/.vim"
  #     state: link
      
  become: yes