---
- block:
    - name: Clone Powerline fonts installer
      git:
        repo: https://github.com/powerline/fonts.git
        dest: "{{ home_path }}/fonts"

    - name: Run Powerline fonts installer
      shell: "{{ home_path }}/fonts/install.sh"
      register: font_install

    - debug:
        var: font_install.stdout_lines

    - name: Tidy up Powerline fonts installer
      file:
        path: "{{ home_path }}/fonts"
        state: absent

  become: yes