---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  changed_when: false

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ apt_packages_to_remove }}"
    state: absent
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: true
  when: update_all_packages | bool

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  become: true
  failed_when: false
