#  Useful stuff for future ideas:
#  * https://github.com/Addvilz/dots/blob/master/roles/workstation/tasks/main.yml

apt_packages:
  - build-essential
  - byobu
  - cmatrix
  - cowsay
  - curl
  - git
  - git-core
  - git-extras
  - hexedit
  - htop
  - htop
  - jq
  # - neofetch
  # - nmap
  # - rsync
  # - sl
  - tmux
  # - tree
  - vim
  # - vlc
  - wget
  # - zenmap
  - zip
  - zsh
  
apt_packages_to_remove:
  - docker.io

ubuntu_keyserver_keys:
  - '8ED17AF5D7E675EB3EE3BCE98AC3B29174885C03' # AdoptOpenJDK
  - '9DC858229FC7DD38854AE2D88D81803C0EBFCD88' # Docker
  - '54A647F9048D5688D7DA2ABE6A030B21BA07F4FB' # Google Cloud SDK
  - '4CCA1EAF950CEE4AB83976DCA040830F7FAC5991' # Google-1
  - 'EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796' # Google-2
  - '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280' # NodeSource
  - '15058500A0235D97F5D10063B188E2B695BD4743' # php-sury-org
  - 'DBA36B5181D0C816F630E889D980A17457F6FB06' # Signal
  - 'D4040146BE3972509FD57FC71F3045A5DF7587C3' # Skype
  - 'DB085A08CA13B8ACB917E0F6D938EC0D038651BD' # Slack
  - '8FD3D9A8D3800305A9FFF259D1742AD60D811D58' # Spotify
  - 'B9F8D658297AF3EFC18D5CDFA2F683C52980AECF' # Virtualbox
  - '72ECF46A56B4AD39C907BBB71646B01B86E50310' # Yarn

apt_repositories:
  - { file: 'adoptopenjdk', repo: 'deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ubuntu_distribution}} main' }
  - { file: 'atom-editor', repo: 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main' }
  - { file: 'docker', repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ubuntu_distribution}} stable' }
  - { file: 'google-chrome', repo: 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main' }
  - { file: 'google-cloud-sdk', repo: 'deb https://packages.cloud.google.com/apt cloud-sdk main' }
  - { file: 'insomnia', repo: 'deb https://dl.bintray.com/getinsomnia/Insomnia /' }
  - { file: 'libkafe', repo: 'deb https://dl.cloudsmith.io/public/kafe/libkafe/deb/debian {{ubuntu_distribution}} main' }
  - { file: 'lynis', repo: 'deb https://packages.cisofy.com/community/lynis/deb/ stable main' }
  - { file: 'mongodb-4.2', repo: 'deb http://repo.mongodb.org/apt/debian {{ubuntu_distribution}}/mongodb-org/4.2 main' }
  - { file: 'nodejs', repo: 'deb https://deb.nodesource.com/node_12.x {{ubuntu_distribution}} main' }
  - { file: 'php-sury-org', repo: 'deb https://packages.sury.org/php/ {{ubuntu_distribution}} main' }
  - { file: 'signal', repo: 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' }
  - { file: 'skype', repo: 'deb [arch=amd64] https://repo.skype.com/deb stable main' }
  - { file: 'slack', repo: 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main' }
  - { file: 'spotify', repo: 'deb http://repository.spotify.com stable non-free' } # HTTP :(
  - { file: 'virtualbox', repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ubuntu_distribution}} contrib' }
  - { file: 'yarn', repo: 'deb https://dl.yarnpkg.com/debian/ stable main' }

ppa_repositories:
  - "ppa:pmjdebruijn/darktable-release"
  - "ppa:tista/adapta"

debs:
  - https://go.microsoft.com/fwlink/?LinkID=760868 # vscode
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb