---
# https://github.com/Mayccoll/Gogh
# https://blog.ssdnodes.com/blog/13-smart-terminal-tools-to-level-up-your-linux-servers/
#  Useful stuff for future ideas:
#  * https://github.com/sobolevn/dotfiles/tree/master/macos
#  * https://github.com/sobolevn/dotfiles/blob/master/Brewfile

- block:
  - name: update
    homebrew: update_homebrew=yes

  - name: install taps
    community.general.homebrew_tap:
      name: "{{ homebrew_taps }}"
    loop: "{{ homebrew_taps }}"

  - name: install formulae
    homebrew:
      name: "{{ homebrew_packages }}"
    loop: "{{ homebrew_packages }}"

  - name: install universal ctags
    homebrew:
      name: universal-ctags/universal-ctags/universal-ctags
      install_options: HEAD

  - name: start homebrew services
    command: brew services start {{ item }}
    with_items:
      - syncthing

  - name: install casks
    homebrew_cask:
      name: "{{ homebrew_casks }}"
    loop: "{{ homebrew_casks }}"

  - name: install from app store
    command: mas install {{ item }}
    with_items: "{{ mases }}"

  become: no 
