---
- name: Clone Powerline fonts
  ansible.builtin.git:
    repo: https://github.com/powerline/fonts.git
    dest: /tmp/powerline-fonts
    depth: 1
    version: master

- name: Install Powerline fonts
  ansible.builtin.command: /tmp/powerline-fonts/install.sh
  args:
    creates: "{{ home_path }}/.local/share/fonts/PowerlineSymbols.otf"
  notify: Refresh font cache

- name: Clean up Powerline fonts repo
  ansible.builtin.file:
    path: /tmp/powerline-fonts
    state: absent
